#!/usr/bin/env bash
# Runs the latest debug build as if cargo-frc was installed
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
( cd "$DIR" && cargo build )
DIR+="/../target/debug/cargo-frc"
echo "$DIR frc $1 $2 $3 $4"
$DIR frc $1 $2 $3 $4
