#!/usr/bin/env bash

# This file is part of "first-rust-competition", which is free software: you
# can redistribute it and/or modify it under the terms of the GNU General
# Public License version 3 as published by the Free Software Foundation. See
# <https://www.gnu.org/licenses/> for a copy.

# Runs the latest debug build as if cargo-frc was installed
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
( cd "$DIR" && cargo build )
DIR+="/../target/debug/cargo-frc"
echo "$DIR frc $1 $2 $3 $4"
$DIR frc $1 $2 $3 $4
