#!/usr/bin/env bash

# Copyright 2018 First Rust Competition Developers.
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

# Runs the latest debug build as if cargo-frc was installed
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
( cd "$DIR" && cargo build )
DIR+="/../target/debug/cargo-frc"
echo "$DIR frc $1 $2 $3 $4"
$DIR frc $1 $2 $3 $4
