// mod analog_input;
// pub use self::analog_input::AnalogInput;
// mod pdp;
// pub use self::pdp::PowerDistributionPanel;
// pub mod can;
// pub use self::can::Can;
// pub mod dio;
// pub mod ds;
// pub mod encoder;
// pub mod i2c;
// pub mod notifier;
// pub mod observe;
// pub mod pneumatics;
// pub mod pwm;
// pub mod relay;
// mod robot;
// pub use self::robot::*;
// mod robot_base;
// pub use self::robot_base::*;
// pub mod serial;
// pub mod spi;
pub mod hal;
pub mod robot;

pub use wpilib_sys::hal_call;
