name: Publish to Crates.io

on: # TODO Needs to be on tag / release
  release:
    types: [released]

env:
  CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }} # TODO create org secret

jobs: # using jobs to publish everything in parallel
  publish_wpilib:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: cd wpilib
        run: cd wpilib
      - name: Package wpilib
        uses: actions-rs/cargo@v1
        with:
          command: package
      - name: Publish wpilib
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token $CRATESIO_TOKEN ## test this using --dry-run

  publish_cargo-frc:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: cd cargo-frc
        run: cd cargo-frc
      - name: Package cargo-frc
        uses: actions-rs/cargo@v1
        with:
          command: package
      - name: Publish cargo-frc
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token $CRATESIO_TOKEN ## test this using --dry-run

  publish_wpilib-sys:
    # allows dirty packaging and publishing. This is because c bindings are dynamically generated
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - name: cd wpilib-sys
        run: cd wpilib-sys
      - name: Package wpilib-sys
        uses: actions-rs/cargo@v1
        with:
          command: package
          args: --allow-dirty
      - name: Publish wpilib-sys
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --allow-dirty --token $CRATESIO_TOKEN ## test this using --dry-run
